// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtfqmxmmbbfmfpouzqzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0ZnFteG1tYmJmbWZwb3V6cXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxNjI1MDcsImV4cCI6MjA5NDczODUwN30.GKTi0mw7mUGVVelS5u7z4k5dl4MnFfH8e90YCKppgtw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});



