// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fccdsfhsinwczrkpgnbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjY2RzZmhzaW53Y3pya3BnbmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTUwMTUsImV4cCI6MjA3Mzg3MTAxNX0.HKH-qKlLJWUW6XevQnqXa82MpGfRSNFBBpLEls8fxXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});